using UnityEngine;
using HorrorEscape.Audio;
using HorrorEscape.Player;

namespace HorrorEscape.Enemy
{
    /// <summary>
    /// Plays sounds from the Backrooms Entity SFX pack from the entity's position
    /// when it gets near the player.
    /// - The closer it is, the more often (and louder) it makes sounds.
    /// - While chasing, it vocalises much more frequently.
    /// - Sounds heard through walls are muffled with a low-pass filter.
    /// - Stays silent while the entity is dormant (Phase 1), so the threat is only
    ///   introduced from Phase 2 onward as designed.
    /// Clips come from AudioManager.entityClips, so this component needs no setup
    /// and survives the stalker being regenerated by the level setup tools.
    /// </summary>
    [RequireComponent(typeof(StalkerAI))]
    public class EntityProximityAudio : MonoBehaviour
    {
        [Header("Range")]
        [Tooltip("The player starts hearing the entity inside this distance.")]
        [SerializeField] private float hearingRange = 22f;
        [Tooltip("Inside this distance the entity is considered 'very close'.")]
        [SerializeField] private float closeRange = 6f;

        [Header("Timing (seconds between sounds)")]
        [SerializeField] private Vector2 farInterval = new Vector2(9f, 14f);
        [SerializeField] private Vector2 closeInterval = new Vector2(3.5f, 6f);
        [SerializeField] private Vector2 chaseInterval = new Vector2(2.5f, 4.5f);

        [Header("Volume")]
        [SerializeField, Range(0f, 1f)] private float farVolume = 0.55f;
        [SerializeField, Range(0f, 1f)] private float closeVolume = 1.0f;
        [SerializeField] private Vector2 pitchRange = new Vector2(0.9f, 1.05f);

        [Header("Wall Occlusion")]
        [SerializeField] private bool muffleThroughWalls = true;
        [SerializeField] private float muffledCutoff = 1400f;
        [SerializeField] private LayerMask occlusionMask = ~0;

        private StalkerAI stalker;
        private AudioSource voice;
        private AudioLowPassFilter lowPass;
        private Transform player;
        private float nextSoundTimer;
        private float occlusionCheckTimer;
        private float targetCutoff = 22000f;

        private void Awake()
        {
            stalker = GetComponent<StalkerAI>();

            voice = gameObject.AddComponent<AudioSource>();
            voice.playOnAwake = false;
            voice.loop = false;
            voice.spatialBlend = 1f;            // Fully 3D: player can tell which direction it is
            voice.rolloffMode = AudioRolloffMode.Linear;
            voice.minDistance = 2f;
            voice.maxDistance = hearingRange + 6f;
            voice.dopplerLevel = 0f;
            voice.spread = 60f;
            voice.priority = 64;

            if (muffleThroughWalls)
            {
                lowPass = gameObject.AddComponent<AudioLowPassFilter>();
                lowPass.cutoffFrequency = 22000f;
            }

            nextSoundTimer = Random.Range(2f, 5f);
        }

        private void Update()
        {
            if (stalker == null || stalker.CurrentState == StalkerState.Dead) return;

            if (player == null)
            {
                FirstPersonController fpc = FindFirstObjectByType<FirstPersonController>();
                if (fpc == null) return;
                player = fpc.transform;
            }

            UpdateOcclusion();

            if (stalker.IsDormant || AudioManager.Instance == null || !AudioManager.Instance.HasEntityClips) return;

            float dist = Vector3.Distance(transform.position, player.position);
            if (dist > hearingRange) return;

            nextSoundTimer -= Time.deltaTime;
            if (nextSoundTimer > 0f || voice.isPlaying) return;

            // 0 = edge of hearing range, 1 = right next to the player
            float closeness = 1f - Mathf.InverseLerp(closeRange, hearingRange, dist);
            PlayEntitySound(Mathf.Lerp(farVolume, closeVolume, closeness));

            Vector2 interval = stalker.CurrentState == StalkerState.Chase
                ? chaseInterval
                : new Vector2(Mathf.Lerp(farInterval.x, closeInterval.x, closeness),
                              Mathf.Lerp(farInterval.y, closeInterval.y, closeness));
            nextSoundTimer = Random.Range(interval.x, interval.y);
        }

        /// <summary>Immediate vocalisation for key moments (spotting the player, getting shot, dying).</summary>
        public void PlayReaction(float volume = 1f)
        {
            if (AudioManager.Instance == null || !AudioManager.Instance.HasEntityClips) return;
            voice.Stop();
            PlayEntitySound(volume);
            nextSoundTimer = Mathf.Max(nextSoundTimer, chaseInterval.x);
        }

        private void PlayEntitySound(float volume)
        {
            AudioClip clip = AudioManager.Instance.GetRandomEntityClip();
            if (clip == null) return;

            voice.clip = clip;
            voice.volume = volume;
            voice.pitch = Random.Range(pitchRange.x, pitchRange.y);
            voice.Play();
        }

        private void UpdateOcclusion()
        {
            if (lowPass == null || player == null) return;

            occlusionCheckTimer -= Time.deltaTime;
            if (occlusionCheckTimer <= 0f)
            {
                occlusionCheckTimer = 0.2f;
                Vector3 from = transform.position + Vector3.up * 1.6f;
                Vector3 to = player.position + Vector3.up * 1.5f;
                bool blocked = false;

                if (Physics.Linecast(from, to, out RaycastHit hit, occlusionMask, QueryTriggerInteraction.Ignore))
                {
                    // Ignore hits on the entity itself or on the player
                    blocked = !hit.transform.IsChildOf(transform) && !hit.transform.IsChildOf(player);
                }
                targetCutoff = blocked ? muffledCutoff : 22000f;
            }

            lowPass.cutoffFrequency = Mathf.Lerp(lowPass.cutoffFrequency, targetCutoff, Time.deltaTime * 6f);
        }
    }
}
